//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debra_client.EmployeeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.EmployeeServiceSoap")]
    public interface EmployeeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccepteEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AccepteEvent(int eventid, bool isaccepted, decimal cocommission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccepteEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AccepteEventAsync(int eventid, bool isaccepted, decimal cocommission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Debra_client.EmployeeService.Event[] GetNewEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.EmployeeService.Event[]> GetNewEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnersSalesByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Debra_client.EmployeeService.SalesRecord[] GetPartnersSalesByID(int partnerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnersSalesByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.EmployeeService.SalesRecord[]> GetPartnersSalesByIDAsync(int partnerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPartnersSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Debra_client.EmployeeService.SalesRecord[] GetAllPartnersSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPartnersSales", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.EmployeeService.SalesRecord[]> GetAllPartnersSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Debra_client.EmployeeService.User[] GetAllUsers(string usertype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.EmployeeService.User[]> GetAllUsersAsync(string usertype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SetUserStatus(int userid, bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SetUserStatusAsync(int userid, bool status);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Event : Partner {
        
        private int eventIDField;
        
        private int partnerIDField;
        
        private decimal commissionField;
        
        private decimal revenuField;
        
        private string eventNameField;
        
        private string venueField;
        
        private string imageUrlField;
        
        private bool isAcceptedField;
        
        private System.DateTime dateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PartnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
                this.RaisePropertyChanged("PartnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
                this.RaisePropertyChanged("Commission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Revenu {
            get {
                return this.revenuField;
            }
            set {
                this.revenuField = value;
                this.RaisePropertyChanged("Revenu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("EventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
                this.RaisePropertyChanged("Venue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
                this.RaisePropertyChanged("ImageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsAccepted {
            get {
                return this.isAcceptedField;
            }
            set {
                this.isAcceptedField = value;
                this.RaisePropertyChanged("IsAccepted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("DateTime");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Partner : User {
        
        private int partnterIDField;
        
        private string companyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PartnterID {
            get {
                return this.partnterIDField;
            }
            set {
                this.partnterIDField = value;
                this.RaisePropertyChanged("PartnterID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Customer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Partner))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int useridField;
        
        private string emailField;
        
        private string passwordField;
        
        private string userTypeField;
        
        private bool statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
                this.RaisePropertyChanged("Userid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("UserType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eventIDField;
        
        private int ticketsSoldField;
        
        private int commissionField;
        
        private int partneridField;
        
        private string eventnameField;
        
        private string venueField;
        
        private string companynameField;
        
        private decimal totalsalesField;
        
        private decimal commissionrateField;
        
        private decimal totalcommissionField;
        
        private decimal aftercommissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TicketsSold {
            get {
                return this.ticketsSoldField;
            }
            set {
                this.ticketsSoldField = value;
                this.RaisePropertyChanged("TicketsSold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
                this.RaisePropertyChanged("Commission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Partnerid {
            get {
                return this.partneridField;
            }
            set {
                this.partneridField = value;
                this.RaisePropertyChanged("Partnerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Eventname {
            get {
                return this.eventnameField;
            }
            set {
                this.eventnameField = value;
                this.RaisePropertyChanged("Eventname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
                this.RaisePropertyChanged("Venue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Companyname {
            get {
                return this.companynameField;
            }
            set {
                this.companynameField = value;
                this.RaisePropertyChanged("Companyname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Totalsales {
            get {
                return this.totalsalesField;
            }
            set {
                this.totalsalesField = value;
                this.RaisePropertyChanged("Totalsales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Commissionrate {
            get {
                return this.commissionrateField;
            }
            set {
                this.commissionrateField = value;
                this.RaisePropertyChanged("Commissionrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Totalcommission {
            get {
                return this.totalcommissionField;
            }
            set {
                this.totalcommissionField = value;
                this.RaisePropertyChanged("Totalcommission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Aftercommission {
            get {
                return this.aftercommissionField;
            }
            set {
                this.aftercommissionField = value;
                this.RaisePropertyChanged("Aftercommission");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : User {
        
        private int employeeIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer : User {
        
        private int customerIDField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("Firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceSoapChannel : Debra_client.EmployeeService.EmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceSoapClient : System.ServiceModel.ClientBase<Debra_client.EmployeeService.EmployeeServiceSoap>, Debra_client.EmployeeService.EmployeeServiceSoap {
        
        public EmployeeServiceSoapClient() {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AccepteEvent(int eventid, bool isaccepted, decimal cocommission) {
            return base.Channel.AccepteEvent(eventid, isaccepted, cocommission);
        }
        
        public System.Threading.Tasks.Task<bool> AccepteEventAsync(int eventid, bool isaccepted, decimal cocommission) {
            return base.Channel.AccepteEventAsync(eventid, isaccepted, cocommission);
        }
        
        public Debra_client.EmployeeService.Event[] GetNewEvents() {
            return base.Channel.GetNewEvents();
        }
        
        public System.Threading.Tasks.Task<Debra_client.EmployeeService.Event[]> GetNewEventsAsync() {
            return base.Channel.GetNewEventsAsync();
        }
        
        public Debra_client.EmployeeService.SalesRecord[] GetPartnersSalesByID(int partnerid) {
            return base.Channel.GetPartnersSalesByID(partnerid);
        }
        
        public System.Threading.Tasks.Task<Debra_client.EmployeeService.SalesRecord[]> GetPartnersSalesByIDAsync(int partnerid) {
            return base.Channel.GetPartnersSalesByIDAsync(partnerid);
        }
        
        public Debra_client.EmployeeService.SalesRecord[] GetAllPartnersSales() {
            return base.Channel.GetAllPartnersSales();
        }
        
        public System.Threading.Tasks.Task<Debra_client.EmployeeService.SalesRecord[]> GetAllPartnersSalesAsync() {
            return base.Channel.GetAllPartnersSalesAsync();
        }
        
        public Debra_client.EmployeeService.User[] GetAllUsers(string usertype) {
            return base.Channel.GetAllUsers(usertype);
        }
        
        public System.Threading.Tasks.Task<Debra_client.EmployeeService.User[]> GetAllUsersAsync(string usertype) {
            return base.Channel.GetAllUsersAsync(usertype);
        }
        
        public bool SetUserStatus(int userid, bool status) {
            return base.Channel.SetUserStatus(userid, status);
        }
        
        public System.Threading.Tasks.Task<bool> SetUserStatusAsync(int userid, bool status) {
            return base.Channel.SetUserStatusAsync(userid, status);
        }
    }
}
