//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debra_client.PartnerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartnerService.PartnerServiceSoap")]
    public interface PartnerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CreateEvent(int partnerid, string eventName, string venue, string imageUrl, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateEventAsync(int partnerid, string eventName, string venue, string imageUrl, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnersEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.PartnerService.Event[] GetPartnersEvents(int partnerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnersEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.PartnerService.Event[]> GetPartnersEventsAsync(int partnerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.PartnerService.Event[] GetEventsByID(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventsByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.PartnerService.Event[]> GetEventsByIDAsync(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.PartnerService.Event[] GetEventByStatus(bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventByStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.PartnerService.Event[]> GetEventByStatusAsync(bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        bool DeleteEvent(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteEventAsync(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpadateEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        bool UpadateEvent(int eventid, string eventname, string venue, string imageurl, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpadateEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpadateEventAsync(int eventid, string eventname, string venue, string imageurl, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        bool CreateTicket(int eventid, int price, int quantity, string type, bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateTicketAsync(int eventid, int price, int quantity, string type, bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        bool UpdateTicket(string type, int price, int quantity, bool status, int ticketid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateTicketAsync(string type, int price, int quantity, bool status, int ticketid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        bool DeleteTicket(int ticketid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteTicketAsync(int ticketid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.PartnerService.Ticket[] GetTicketByID(int ticketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.PartnerService.Ticket[]> GetTicketByIDAsync(int ticketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.PartnerService.Ticket[] GetEventTicket(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.PartnerService.Ticket[]> GetEventTicketAsync(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnersSalesByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.PartnerService.SalesRecord[] GetPartnersSalesByID(int partnerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnersSalesByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.PartnerService.SalesRecord[]> GetPartnersSalesByIDAsync(int partnerid);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Event : Partner {
        
        private int eventIDField;
        
        private int partnerIDField;
        
        private decimal commissionField;
        
        private decimal revenuField;
        
        private string eventNameField;
        
        private string venueField;
        
        private string imageUrlField;
        
        private bool isAcceptedField;
        
        private System.DateTime dateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PartnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
                this.RaisePropertyChanged("PartnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
                this.RaisePropertyChanged("Commission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Revenu {
            get {
                return this.revenuField;
            }
            set {
                this.revenuField = value;
                this.RaisePropertyChanged("Revenu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("EventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
                this.RaisePropertyChanged("Venue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
                this.RaisePropertyChanged("ImageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsAccepted {
            get {
                return this.isAcceptedField;
            }
            set {
                this.isAcceptedField = value;
                this.RaisePropertyChanged("IsAccepted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("DateTime");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Partner : User {
        
        private int partnterIDField;
        
        private string companyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PartnterID {
            get {
                return this.partnterIDField;
            }
            set {
                this.partnterIDField = value;
                this.RaisePropertyChanged("PartnterID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Customer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Partner))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int useridField;
        
        private string emailField;
        
        private string passwordField;
        
        private string userTypeField;
        
        private bool statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
                this.RaisePropertyChanged("Userid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("UserType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eventIDField;
        
        private int ticketsSoldField;
        
        private int commissionField;
        
        private int partneridField;
        
        private string eventnameField;
        
        private string venueField;
        
        private string companynameField;
        
        private decimal totalsalesField;
        
        private decimal commissionrateField;
        
        private decimal totalcommissionField;
        
        private decimal aftercommissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TicketsSold {
            get {
                return this.ticketsSoldField;
            }
            set {
                this.ticketsSoldField = value;
                this.RaisePropertyChanged("TicketsSold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
                this.RaisePropertyChanged("Commission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Partnerid {
            get {
                return this.partneridField;
            }
            set {
                this.partneridField = value;
                this.RaisePropertyChanged("Partnerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Eventname {
            get {
                return this.eventnameField;
            }
            set {
                this.eventnameField = value;
                this.RaisePropertyChanged("Eventname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
                this.RaisePropertyChanged("Venue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Companyname {
            get {
                return this.companynameField;
            }
            set {
                this.companynameField = value;
                this.RaisePropertyChanged("Companyname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Totalsales {
            get {
                return this.totalsalesField;
            }
            set {
                this.totalsalesField = value;
                this.RaisePropertyChanged("Totalsales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Commissionrate {
            get {
                return this.commissionrateField;
            }
            set {
                this.commissionrateField = value;
                this.RaisePropertyChanged("Commissionrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Totalcommission {
            get {
                return this.totalcommissionField;
            }
            set {
                this.totalcommissionField = value;
                this.RaisePropertyChanged("Totalcommission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Aftercommission {
            get {
                return this.aftercommissionField;
            }
            set {
                this.aftercommissionField = value;
                this.RaisePropertyChanged("Aftercommission");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ticket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ticketIDField;
        
        private int eventIDField;
        
        private int priceField;
        
        private int quantityField;
        
        private int availableQuantityField;
        
        private string typeField;
        
        private bool statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TicketID {
            get {
                return this.ticketIDField;
            }
            set {
                this.ticketIDField = value;
                this.RaisePropertyChanged("TicketID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int AvailableQuantity {
            get {
                return this.availableQuantityField;
            }
            set {
                this.availableQuantityField = value;
                this.RaisePropertyChanged("AvailableQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : User {
        
        private int employeeIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer : User {
        
        private int customerIDField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("Firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PartnerServiceSoapChannel : Debra_client.PartnerService.PartnerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartnerServiceSoapClient : System.ServiceModel.ClientBase<Debra_client.PartnerService.PartnerServiceSoap>, Debra_client.PartnerService.PartnerServiceSoap {
        
        public PartnerServiceSoapClient() {
        }
        
        public PartnerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartnerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartnerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartnerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateEvent(int partnerid, string eventName, string venue, string imageUrl, System.DateTime dateTime) {
            return base.Channel.CreateEvent(partnerid, eventName, venue, imageUrl, dateTime);
        }
        
        public System.Threading.Tasks.Task<bool> CreateEventAsync(int partnerid, string eventName, string venue, string imageUrl, System.DateTime dateTime) {
            return base.Channel.CreateEventAsync(partnerid, eventName, venue, imageUrl, dateTime);
        }
        
        public Debra_client.PartnerService.Event[] GetPartnersEvents(int partnerid) {
            return base.Channel.GetPartnersEvents(partnerid);
        }
        
        public System.Threading.Tasks.Task<Debra_client.PartnerService.Event[]> GetPartnersEventsAsync(int partnerid) {
            return base.Channel.GetPartnersEventsAsync(partnerid);
        }
        
        public Debra_client.PartnerService.Event[] GetEventsByID(int eventid) {
            return base.Channel.GetEventsByID(eventid);
        }
        
        public System.Threading.Tasks.Task<Debra_client.PartnerService.Event[]> GetEventsByIDAsync(int eventid) {
            return base.Channel.GetEventsByIDAsync(eventid);
        }
        
        public Debra_client.PartnerService.Event[] GetEventByStatus(bool status) {
            return base.Channel.GetEventByStatus(status);
        }
        
        public System.Threading.Tasks.Task<Debra_client.PartnerService.Event[]> GetEventByStatusAsync(bool status) {
            return base.Channel.GetEventByStatusAsync(status);
        }
        
        public bool DeleteEvent(int eventid) {
            return base.Channel.DeleteEvent(eventid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEventAsync(int eventid) {
            return base.Channel.DeleteEventAsync(eventid);
        }
        
        public bool UpadateEvent(int eventid, string eventname, string venue, string imageurl, System.DateTime dateTime) {
            return base.Channel.UpadateEvent(eventid, eventname, venue, imageurl, dateTime);
        }
        
        public System.Threading.Tasks.Task<bool> UpadateEventAsync(int eventid, string eventname, string venue, string imageurl, System.DateTime dateTime) {
            return base.Channel.UpadateEventAsync(eventid, eventname, venue, imageurl, dateTime);
        }
        
        public bool CreateTicket(int eventid, int price, int quantity, string type, bool statues) {
            return base.Channel.CreateTicket(eventid, price, quantity, type, statues);
        }
        
        public System.Threading.Tasks.Task<bool> CreateTicketAsync(int eventid, int price, int quantity, string type, bool statues) {
            return base.Channel.CreateTicketAsync(eventid, price, quantity, type, statues);
        }
        
        public bool UpdateTicket(string type, int price, int quantity, bool status, int ticketid) {
            return base.Channel.UpdateTicket(type, price, quantity, status, ticketid);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTicketAsync(string type, int price, int quantity, bool status, int ticketid) {
            return base.Channel.UpdateTicketAsync(type, price, quantity, status, ticketid);
        }
        
        public bool DeleteTicket(int ticketid) {
            return base.Channel.DeleteTicket(ticketid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTicketAsync(int ticketid) {
            return base.Channel.DeleteTicketAsync(ticketid);
        }
        
        public Debra_client.PartnerService.Ticket[] GetTicketByID(int ticketID) {
            return base.Channel.GetTicketByID(ticketID);
        }
        
        public System.Threading.Tasks.Task<Debra_client.PartnerService.Ticket[]> GetTicketByIDAsync(int ticketID) {
            return base.Channel.GetTicketByIDAsync(ticketID);
        }
        
        public Debra_client.PartnerService.Ticket[] GetEventTicket(int eventid) {
            return base.Channel.GetEventTicket(eventid);
        }
        
        public System.Threading.Tasks.Task<Debra_client.PartnerService.Ticket[]> GetEventTicketAsync(int eventid) {
            return base.Channel.GetEventTicketAsync(eventid);
        }
        
        public Debra_client.PartnerService.SalesRecord[] GetPartnersSalesByID(int partnerid) {
            return base.Channel.GetPartnersSalesByID(partnerid);
        }
        
        public System.Threading.Tasks.Task<Debra_client.PartnerService.SalesRecord[]> GetPartnersSalesByIDAsync(int partnerid) {
            return base.Channel.GetPartnersSalesByIDAsync(partnerid);
        }
    }
}
