//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debra_client.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.CustomerServiceSoap")]
    public interface CustomerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateSale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CreateSale(int customerid, int ticketid, int quantity, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateSale", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateSaleAsync(int customerid, int ticketid, int quantity, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.CustomerService.Event[] GetEventByStatus(bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventByStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.CustomerService.Event[]> GetEventByStatusAsync(bool status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.CustomerService.Event[] GetEventByID(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.CustomerService.Event[]> GetEventByIDAsync(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.CustomerService.Ticket[] GetEventTicket(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.CustomerService.Ticket[]> GetEventTicketAsync(int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        Debra_client.CustomerService.Event[] GetPurchase(int CustomreID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchase", ReplyAction="*")]
        System.Threading.Tasks.Task<Debra_client.CustomerService.Event[]> GetPurchaseAsync(int CustomreID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Event : Partner {
        
        private int eventIDField;
        
        private int partnerIDField;
        
        private decimal commissionField;
        
        private decimal revenuField;
        
        private string eventNameField;
        
        private string venueField;
        
        private string imageUrlField;
        
        private bool isAcceptedField;
        
        private System.DateTime dateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PartnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
                this.RaisePropertyChanged("PartnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
                this.RaisePropertyChanged("Commission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Revenu {
            get {
                return this.revenuField;
            }
            set {
                this.revenuField = value;
                this.RaisePropertyChanged("Revenu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("EventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
                this.RaisePropertyChanged("Venue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
                this.RaisePropertyChanged("ImageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsAccepted {
            get {
                return this.isAcceptedField;
            }
            set {
                this.isAcceptedField = value;
                this.RaisePropertyChanged("IsAccepted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("DateTime");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Partner : User {
        
        private int partnterIDField;
        
        private string companyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PartnterID {
            get {
                return this.partnterIDField;
            }
            set {
                this.partnterIDField = value;
                this.RaisePropertyChanged("PartnterID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Customer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Partner))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int useridField;
        
        private string emailField;
        
        private string passwordField;
        
        private string userTypeField;
        
        private bool statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
                this.RaisePropertyChanged("Userid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("UserType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ticket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ticketIDField;
        
        private int eventIDField;
        
        private int priceField;
        
        private int quantityField;
        
        private int availableQuantityField;
        
        private string typeField;
        
        private bool statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TicketID {
            get {
                return this.ticketIDField;
            }
            set {
                this.ticketIDField = value;
                this.RaisePropertyChanged("TicketID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int AvailableQuantity {
            get {
                return this.availableQuantityField;
            }
            set {
                this.availableQuantityField = value;
                this.RaisePropertyChanged("AvailableQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : User {
        
        private int employeeIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer : User {
        
        private int customerIDField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("Firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceSoapChannel : Debra_client.CustomerService.CustomerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceSoapClient : System.ServiceModel.ClientBase<Debra_client.CustomerService.CustomerServiceSoap>, Debra_client.CustomerService.CustomerServiceSoap {
        
        public CustomerServiceSoapClient() {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateSale(int customerid, int ticketid, int quantity, decimal total) {
            return base.Channel.CreateSale(customerid, ticketid, quantity, total);
        }
        
        public System.Threading.Tasks.Task<bool> CreateSaleAsync(int customerid, int ticketid, int quantity, decimal total) {
            return base.Channel.CreateSaleAsync(customerid, ticketid, quantity, total);
        }
        
        public Debra_client.CustomerService.Event[] GetEventByStatus(bool status) {
            return base.Channel.GetEventByStatus(status);
        }
        
        public System.Threading.Tasks.Task<Debra_client.CustomerService.Event[]> GetEventByStatusAsync(bool status) {
            return base.Channel.GetEventByStatusAsync(status);
        }
        
        public Debra_client.CustomerService.Event[] GetEventByID(int eventid) {
            return base.Channel.GetEventByID(eventid);
        }
        
        public System.Threading.Tasks.Task<Debra_client.CustomerService.Event[]> GetEventByIDAsync(int eventid) {
            return base.Channel.GetEventByIDAsync(eventid);
        }
        
        public Debra_client.CustomerService.Ticket[] GetEventTicket(int eventid) {
            return base.Channel.GetEventTicket(eventid);
        }
        
        public System.Threading.Tasks.Task<Debra_client.CustomerService.Ticket[]> GetEventTicketAsync(int eventid) {
            return base.Channel.GetEventTicketAsync(eventid);
        }
        
        public Debra_client.CustomerService.Event[] GetPurchase(int CustomreID) {
            return base.Channel.GetPurchase(CustomreID);
        }
        
        public System.Threading.Tasks.Task<Debra_client.CustomerService.Event[]> GetPurchaseAsync(int CustomreID) {
            return base.Channel.GetPurchaseAsync(CustomreID);
        }
    }
}
